import { Injectable } from '@angular/core'

@Injectable()
export class MessagesService {
  getMessages () {
    return [
      {
        id: 1,
        title: "1 Carta da Casa Universal de Justiça aos participantes da dedicação do Templo no Chile",
        paragraphs: [
          {text: "[Tradução]", class: "bold heading-1"},
          {text: "14 de outubro de 2016", class: "right heading-2"},
          {text: "Aos amigos reunidos em Santiago do Chile, para a dedicação do Templo Mãe da América do Sul", class: "heading-3"},
          {text: "Amigos ternamente amados,", class: "italic underline"},
          {counter: 1, text: "Nós os saudamos com imensa alegria nessa ocasião singular, um momento de grande vitória para o mundo bahá´í, depois de muito esforço árduo. O processo de erigir Casas de Adoração bahá´ís, um empreendimento cujas origens se remontam aos tempos da própria Abençoada Beleza, atingiu o ponto no qual hoje um Templo Mãe está erguido no solo de cada continente. Três desses Templos estão agora sobre um eixo pan-americano, a cujo pólo meridional todos vocês foram atraídos. Assim como previsto pelo Guardião, a capital chilena se tornou o local do primeiro Mashriqu\'1-Adhkar da América do Sul. Combinando delicadeza e grandeza em igual medida, este Ponto do Alvorecer da Lembrança de Deus agora convoca a todos os que chegam a adorar Aquele Que é seu Criador, seu Senhor soberano, Quem dá Luz ao mundo.",},
          {counter: 2, text: "As poderosas declarações no Kitáb-i-Aqdas dirigidas aos presidentes das repúblicas das Américas, que se somam ao mandato dado pelo Báb para todos os \"povos do Ocidente\" para ajudar Sua Causa, conferem honra e obrigações inefáveis sobre estes países do norte e do sul. Essas palavras fecundas pressagiaram a íntima associação da América do Sul com a Fé. Recordamos com profunda admiração os atos heróicos e sacrificados daqueles primeiros crentes que introduziram neste continente o nome de Bahá´u´lláh. Com sua determinação inflamada pelo chamado do Mestre em Suas Epístolas que delineiam o Plano Divino e instados por Shoghi Effendi através sucessivas diretrizes que ele deu para a persecução do Plano, pioneiros viajaram para as nações da América Latina e começaram a nutrir comunidades que puderam manter Assembleias Locais e, finalmente, Assembleias Espirituais Nacionais – comunidades que vieram a ser designadas pelo Guardião como \"colaboradoras dos executores principais do Plano Divino legado por ‘Abdu´l-Bahá\". O sucesso dos esforços de ensino em larga escala revelaram a pureza e a mente aberta dos habitantes do continente em toda a sua diversidade, e sua evidente receptividade ao impulso divino. Um dos distintivos mais notáveis daquele período foi o entusiasmo com o qual povos indígenas abraçaram a visão de Bahá´u´lláh e Sua Fé, reconhecendo o poder de Sua Palavra para liberar a alma e transformar a sociedade. Havendo realizado tais avanços, os amigos assumiram o desafio de aprender como manter um processo de rápida expansão e consolidação. Percepções que emergiram da experiência acumulada nesta região beneficiaram a totalidade do mundo bahá´í e atualmente, esforços dos crentes sul-americanos para difundir a Fé e construir comunidades sobre fundações espirituais são uma contínua fonte de inspiração. Quão apropriado, então, que no momento em que povos e nações do hemisfério ocidental estão necessitados, mais que nunca, da iluminação trazida pelos ensinamentos do Mensageiro universal de Deus, um poderoso farol espiritual brilha com todo o seu esplendor no sopé dos Andes.",},
          {counter: 3, text: "O Mashriqu\'l-Adhkar é \"uma das instituições mais vitais do mundo\". Um Templo e suas dependências associadas personificam os dois aspectos essenciais e inseparáveis da vida bahá´í: adoração e serviço. Como um potente símbolo e um elemento integrante da civilização divina para a qual a Revelação de Bahá´u´lláh conduz todos os povos, a Casa de adoração se converte no ponto focal da comunidade da qual emerge. \"As santas fragrâncias do Mashriqu\'l-Adhkar\", explica ‘Abdu\'l-Bahá, \"vivificam as almas dos retos e suas brisas vitalizadoras conferem vida aos puros de coração\". De fato, sua influência é tal que galvaniza um povo inteiro a alcançar um senso de propósito unificado mais profundo. O olhar do mundo bahá’í neste momento está fixado em seu Templo recém dedicado, e estamos certos de que esta vitória tão anelada trará júbilo aos amigos em todas as partes. No entanto, certamente não se contentarão em simplesmente regozijar entre si mesmos. Inspirados por tudo o que este sublime edifício representa, convidarão a outros a descobrir a alegria duradoura que vem do louvor à Deus e do serviço à humanidade.",},
          {counter: 4, text: "Inclinamos nossas cabeças no Limiar da Antiga Beleza, e Lhe damos graças por haver permitido a Seus devotos seguidores construir tão notável Templo, forjado em vidro, pedra e luz, nutrindo uma atração pelo sagrado. A gratidão que sentimos aumenta nosso anelo por aquele dia glorioso quando a bênção de um Mashriqu\'l-Adhkár será conferida a todas as cidades e povoados, e nos voltamos esperançosos para aqueles países onde Casas de Adoração nacionais e locais estão começando a surgir. Que a visão resplandecente do que a comunidade do Nome Supremo realizou agora em Santiago, impulsione os fiéis em todas as partes para que intensifiquem seus serviços, não importa quão humildes sejam, prestados para a melhora do mundo, oferecidos à Glória de Deus.",},
          {text: "This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. ", class: "quote"},
          {text: "[assina: A Casa Universal de Justiça]", class: "right"},
        ],
      },
      {
        id: 2,
        title: "2 Carta da Casa Universal de Justiça aos participantes da dedicação do Templo no Chile",
        paragraphs: [
          {text: "[Tradução]", class: "bold heading-1"},
          {text: "14 de outubro de 2016", class: "right heading-2"},
          {text: "Aos amigos reunidos em Santiago do Chile, para a dedicação do Templo Mãe da América do Sul", class: "heading-3"},
          {text: "Amigos ternamente amados,", class: "italic underline"},
          {counter: 1, text: "Nós os saudamos com imensa alegria nessa ocasião singular, um momento de grande vitória para o mundo bahá´í, depois de muito esforço árduo. O processo de erigir Casas de Adoração bahá´ís, um empreendimento cujas origens se remontam aos tempos da própria Abençoada Beleza, atingiu o ponto no qual hoje um Templo Mãe está erguido no solo de cada continente. Três desses Templos estão agora sobre um eixo pan-americano, a cujo pólo meridional todos vocês foram atraídos. Assim como previsto pelo Guardião, a capital chilena se tornou o local do primeiro Mashriqu\'1-Adhkar da América do Sul. Combinando delicadeza e grandeza em igual medida, este Ponto do Alvorecer da Lembrança de Deus agora convoca a todos os que chegam a adorar Aquele Que é seu Criador, seu Senhor soberano, Quem dá Luz ao mundo.",},
          {counter: 2, text: "As poderosas declarações no Kitáb-i-Aqdas dirigidas aos presidentes das repúblicas das Américas, que se somam ao mandato dado pelo Báb para todos os \"povos do Ocidente\" para ajudar Sua Causa, conferem honra e obrigações inefáveis sobre estes países do norte e do sul. Essas palavras fecundas pressagiaram a íntima associação da América do Sul com a Fé. Recordamos com profunda admiração os atos heróicos e sacrificados daqueles primeiros crentes que introduziram neste continente o nome de Bahá´u´lláh. Com sua determinação inflamada pelo chamado do Mestre em Suas Epístolas que delineiam o Plano Divino e instados por Shoghi Effendi através sucessivas diretrizes que ele deu para a persecução do Plano, pioneiros viajaram para as nações da América Latina e começaram a nutrir comunidades que puderam manter Assembleias Locais e, finalmente, Assembleias Espirituais Nacionais – comunidades que vieram a ser designadas pelo Guardião como \"colaboradoras dos executores principais do Plano Divino legado por ‘Abdu´l-Bahá\". O sucesso dos esforços de ensino em larga escala revelaram a pureza e a mente aberta dos habitantes do continente em toda a sua diversidade, e sua evidente receptividade ao impulso divino. Um dos distintivos mais notáveis daquele período foi o entusiasmo com o qual povos indígenas abraçaram a visão de Bahá´u´lláh e Sua Fé, reconhecendo o poder de Sua Palavra para liberar a alma e transformar a sociedade. Havendo realizado tais avanços, os amigos assumiram o desafio de aprender como manter um processo de rápida expansão e consolidação. Percepções que emergiram da experiência acumulada nesta região beneficiaram a totalidade do mundo bahá´í e atualmente, esforços dos crentes sul-americanos para difundir a Fé e construir comunidades sobre fundações espirituais são uma contínua fonte de inspiração. Quão apropriado, então, que no momento em que povos e nações do hemisfério ocidental estão necessitados, mais que nunca, da iluminação trazida pelos ensinamentos do Mensageiro universal de Deus, um poderoso farol espiritual brilha com todo o seu esplendor no sopé dos Andes.",},
          {counter: 3, text: "O Mashriqu\'l-Adhkar é \"uma das instituições mais vitais do mundo\". Um Templo e suas dependências associadas personificam os dois aspectos essenciais e inseparáveis da vida bahá´í: adoração e serviço. Como um potente símbolo e um elemento integrante da civilização divina para a qual a Revelação de Bahá´u´lláh conduz todos os povos, a Casa de adoração se converte no ponto focal da comunidade da qual emerge. \"As santas fragrâncias do Mashriqu\'l-Adhkar\", explica ‘Abdu\'l-Bahá, \"vivificam as almas dos retos e suas brisas vitalizadoras conferem vida aos puros de coração\". De fato, sua influência é tal que galvaniza um povo inteiro a alcançar um senso de propósito unificado mais profundo. O olhar do mundo bahá’í neste momento está fixado em seu Templo recém dedicado, e estamos certos de que esta vitória tão anelada trará júbilo aos amigos em todas as partes. No entanto, certamente não se contentarão em simplesmente regozijar entre si mesmos. Inspirados por tudo o que este sublime edifício representa, convidarão a outros a descobrir a alegria duradoura que vem do louvor à Deus e do serviço à humanidade.",},
          {counter: 4, text: "Inclinamos nossas cabeças no Limiar da Antiga Beleza, e Lhe damos graças por haver permitido a Seus devotos seguidores construir tão notável Templo, forjado em vidro, pedra e luz, nutrindo uma atração pelo sagrado. A gratidão que sentimos aumenta nosso anelo por aquele dia glorioso quando a bênção de um Mashriqu\'l-Adhkár será conferida a todas as cidades e povoados, e nos voltamos esperançosos para aqueles países onde Casas de Adoração nacionais e locais estão começando a surgir. Que a visão resplandecente do que a comunidade do Nome Supremo realizou agora em Santiago, impulsione os fiéis em todas as partes para que intensifiquem seus serviços, não importa quão humildes sejam, prestados para a melhora do mundo, oferecidos à Glória de Deus.",},
          {text: "This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. ", class: "quote"},
          {text: "[assina: A Casa Universal de Justiça]", class: "right"},
        ],
      },
      {
        id: 3,
        title: "3 Carta da Casa Universal de Justiça aos participantes da dedicação do Templo no Chile",
        paragraphs: [
          {text: "[Tradução]", class: "bold heading-1"},
          {text: "14 de outubro de 2016", class: "right heading-2"},
          {text: "Aos amigos reunidos em Santiago do Chile, para a dedicação do Templo Mãe da América do Sul", class: "heading-3"},
          {text: "Amigos ternamente amados,", class: "italic underline"},
          {counter: 1, text: "Nós os saudamos com imensa alegria nessa ocasião singular, um momento de grande vitória para o mundo bahá´í, depois de muito esforço árduo. O processo de erigir Casas de Adoração bahá´ís, um empreendimento cujas origens se remontam aos tempos da própria Abençoada Beleza, atingiu o ponto no qual hoje um Templo Mãe está erguido no solo de cada continente. Três desses Templos estão agora sobre um eixo pan-americano, a cujo pólo meridional todos vocês foram atraídos. Assim como previsto pelo Guardião, a capital chilena se tornou o local do primeiro Mashriqu\'1-Adhkar da América do Sul. Combinando delicadeza e grandeza em igual medida, este Ponto do Alvorecer da Lembrança de Deus agora convoca a todos os que chegam a adorar Aquele Que é seu Criador, seu Senhor soberano, Quem dá Luz ao mundo.",},
          {counter: 2, text: "As poderosas declarações no Kitáb-i-Aqdas dirigidas aos presidentes das repúblicas das Américas, que se somam ao mandato dado pelo Báb para todos os \"povos do Ocidente\" para ajudar Sua Causa, conferem honra e obrigações inefáveis sobre estes países do norte e do sul. Essas palavras fecundas pressagiaram a íntima associação da América do Sul com a Fé. Recordamos com profunda admiração os atos heróicos e sacrificados daqueles primeiros crentes que introduziram neste continente o nome de Bahá´u´lláh. Com sua determinação inflamada pelo chamado do Mestre em Suas Epístolas que delineiam o Plano Divino e instados por Shoghi Effendi através sucessivas diretrizes que ele deu para a persecução do Plano, pioneiros viajaram para as nações da América Latina e começaram a nutrir comunidades que puderam manter Assembleias Locais e, finalmente, Assembleias Espirituais Nacionais – comunidades que vieram a ser designadas pelo Guardião como \"colaboradoras dos executores principais do Plano Divino legado por ‘Abdu´l-Bahá\". O sucesso dos esforços de ensino em larga escala revelaram a pureza e a mente aberta dos habitantes do continente em toda a sua diversidade, e sua evidente receptividade ao impulso divino. Um dos distintivos mais notáveis daquele período foi o entusiasmo com o qual povos indígenas abraçaram a visão de Bahá´u´lláh e Sua Fé, reconhecendo o poder de Sua Palavra para liberar a alma e transformar a sociedade. Havendo realizado tais avanços, os amigos assumiram o desafio de aprender como manter um processo de rápida expansão e consolidação. Percepções que emergiram da experiência acumulada nesta região beneficiaram a totalidade do mundo bahá´í e atualmente, esforços dos crentes sul-americanos para difundir a Fé e construir comunidades sobre fundações espirituais são uma contínua fonte de inspiração. Quão apropriado, então, que no momento em que povos e nações do hemisfério ocidental estão necessitados, mais que nunca, da iluminação trazida pelos ensinamentos do Mensageiro universal de Deus, um poderoso farol espiritual brilha com todo o seu esplendor no sopé dos Andes.",},
          {counter: 3, text: "O Mashriqu\'l-Adhkar é \"uma das instituições mais vitais do mundo\". Um Templo e suas dependências associadas personificam os dois aspectos essenciais e inseparáveis da vida bahá´í: adoração e serviço. Como um potente símbolo e um elemento integrante da civilização divina para a qual a Revelação de Bahá´u´lláh conduz todos os povos, a Casa de adoração se converte no ponto focal da comunidade da qual emerge. \"As santas fragrâncias do Mashriqu\'l-Adhkar\", explica ‘Abdu\'l-Bahá, \"vivificam as almas dos retos e suas brisas vitalizadoras conferem vida aos puros de coração\". De fato, sua influência é tal que galvaniza um povo inteiro a alcançar um senso de propósito unificado mais profundo. O olhar do mundo bahá’í neste momento está fixado em seu Templo recém dedicado, e estamos certos de que esta vitória tão anelada trará júbilo aos amigos em todas as partes. No entanto, certamente não se contentarão em simplesmente regozijar entre si mesmos. Inspirados por tudo o que este sublime edifício representa, convidarão a outros a descobrir a alegria duradoura que vem do louvor à Deus e do serviço à humanidade.",},
          {counter: 4, text: "Inclinamos nossas cabeças no Limiar da Antiga Beleza, e Lhe damos graças por haver permitido a Seus devotos seguidores construir tão notável Templo, forjado em vidro, pedra e luz, nutrindo uma atração pelo sagrado. A gratidão que sentimos aumenta nosso anelo por aquele dia glorioso quando a bênção de um Mashriqu\'l-Adhkár será conferida a todas as cidades e povoados, e nos voltamos esperançosos para aqueles países onde Casas de Adoração nacionais e locais estão começando a surgir. Que a visão resplandecente do que a comunidade do Nome Supremo realizou agora em Santiago, impulsione os fiéis em todas as partes para que intensifiquem seus serviços, não importa quão humildes sejam, prestados para a melhora do mundo, oferecidos à Glória de Deus.",},
          {text: "This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. This is a quote. ", class: "quote"},
          {text: "[assina: A Casa Universal de Justiça]", class: "right"},
        ],
      },
    ]
  }

  getMessage (id) {
    return this.getMessages().filter((message) => message.id == id)[0]
  }
}
